// Dummy data for a Flutter app
List<Map<String, dynamic>> projectData =[
  {
    "id": 1,
    "title": "[Completed in 72 Hours]\nGoa Lawah",
    "about": "Goa Lawah is an Android-based game created for the Global Game Jam 2017 event with the theme 'Waves'. The game features the adventure of a bat exploring a mysterious cave, where players must avoid obstacles in an area that continuously shifts between light and dark.",
    "outcome": ["Completed within 72 Hours", "Lead developer handling all programming", "Released on Google Playstore"],
    "timeline": "January 2017",
    "timeline_detail": "72 Hours of Development",
    "responsibility": "As the solo programmer, I was fully responsible for all the game's code. Additionally, I coordinated with designers, and together we designed the gameplay and determined the visual design for the game.",
    "tech_stack": "Construct 2",
    "app_title": "Goa Lawah",
    "year": "2017",
    "role": "Game Programmer",
    "link": "https://v3.globalgamejam.org/2017/games/goa-lawah",
    "image_path": "assets/images/app_screenshot/goalawah_detail.png",
    "icon_path": "assets/images/app_logo/goalawah_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 2,
    "title": "[Refining the Experience]\nMiNi Depo",
    "about": "MiNi Depo is an app-based marketplace designed to facilitate the trading of building materials. This application allows users to find and purchase building materials online with various features supporting efficient transactions.",
    "outcome": ["App update from V1 to V2", "Released on Google Playstore", "Meets Client Requirements"],
    "timeline": "January 2021 - March 2021",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As an Assistant Designer, I was tasked with revising the design according to client or developer requests and clarifying unclear design details. I also helped add additional designs needed to update the app from version V1 to V2.",
    "tech_stack": "Adobe XD",
    "app_title": "MiNi Depo",
    "year": "2021",
    "role": "Assistant Designer",
    "link": "",
    "image_path": "assets/images/app_screenshot/minidepo_detail.png",
    "icon_path": "assets/images/app_logo/minidepo_thumbnail.png",
    "category": "Application Mockup",
    "device": ["assets/vectors/fluent--design-ideas-16-filled.svg"]
  },
  {
    "id": 3,
    "title": "[Optimizing Workflow Efficiency]\nTimedoor Design System",
    "about": "Timedoor Design System is a starter project for React Native that provides various UI elements like buttons, text fields, and other components that programmers can use to accelerate app development. The system is designed to be easily integrated into any project to enhance development team efficiency.",
    "outcome": ["Timedoor Design System React Native Package", "Updated with a fresher design", "Managed effectively"],
    "timeline": "September 2023 - November 2023",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As the Supervisor of the Research and Development team, I was responsible for organizing task distribution in the development of the Timedoor Design System. I set priorities and ensured the work proceeded according to schedule. Although this project was initially part of the 2023 KPI, higher-priority research caused the project to be discontinued.",
    "tech_stack": "React Native",
    "app_title": "Timedoor Design System",
    "year": "2023",
    "role": "Supervisor",
    "link": "",
    "image_path": "assets/images/app_screenshot/tds_detail.png",
    "icon_path": "assets/images/app_logo/tds_thumbnail.png",
    "category": "Template Mobile Project",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 4,
    "title": "Escape Room Experience\n[Discover Your Path] at Maranatha",
    "about": "Maranatha Trove is a web-based escape room game designed to help prospective students find the most suitable major at Maranatha University. Players must solve puzzles based on provided clues. The game is used as an interactive simulation displayed on Maranatha University's website as part of the new student admission process.",
    "outcome": ["9 Web Games for 9 majors", "Developed game as per client requirements", "Connected the database so all player data is recorded"],
    "timeline": "April 2023 - August 2023",
    "timeline_detail": "4 Months of Development",
    "responsibility": "As a Game Programmer, I was tasked with translating the client's requirements into an interactive and functional game. Additionally, I coordinated with the backend team to integrate this game into Maranatha University's website.",
    "tech_stack": "Contruct 2",
    "app_title": "Maranatha Trove",
    "year": "2023",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/maranatha_detail.png",
    "icon_path": "assets/images/app_logo/maranatha_thumbnail.png",
    "category": "Web Game",
    "device": ["assets/vectors/mdi--web.svg"]
  },
  {
    "id": 5,
    "title": "[Top 10 at DILo Festival]\nAksara",
    "about": "Aksara is an educational game where players must write Balinese characters to destroy falling meteors. The game was designed as part of the DILo Festival 2019 hackathon and made it into the top 10 finalists. The aim of the game is to introduce Balinese script through interactive gameplay utilizing motion detection.",
    "outcome": ["Top 10 in DILo Festival 2019", "Collaboration with Luh Ayu Manik Mas, Bali Superhero", "Development of a motion-detection application for Balinese script"],
    "timeline": "August 2019",
    "timeline_detail": "3 Days of Development",
    "responsibility": "As both Game Designer and Game Programmer, I designed the game concept and was responsible for developing all technical aspects of the game, from idea to programming implementation.",
    "tech_stack": "Construct 2",
    "app_title": "Aksara",
    "year": "2019",
    "role": "Game Designer & Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/aksara_detail.png",
    "icon_path": "assets/images/app_logo/aksara_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 6,
    "title": "[Innovative English Learning Tool]\nGame Cerita Rakyat Bali",
    "about": "Game Cerita Rakyat Bali is an educational game designed to teach English to elementary school students through Balinese folklore. The game contains three stories: 'I Cupak & Gerantang', 'I Sugih & I Tiwas', and 'Manik Angkeran'. Developed as part of research by lecturers and students of the English Department at Undhiksa Singaraja, the game aims to evaluate the effectiveness of using games in English teaching.",
    "outcome": ["Research & Thesis Project for Undhiksa Students", "Converted folklore into interactive media", "Completed within the specified deadline"],
    "timeline": "September 2019 - December 2019",
    "timeline_detail": "4 Months of Development",
    "responsibility": "As a Game Programmer, I was responsible for developing this game according to the specifications provided by the research team. I translated their ideas into a functional and interactive game.",
    "tech_stack": "Construct 2",
    "app_title": "Game Cerita Rakyat Bali",
    "year": "2019",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/cerita_detail.png",
    "icon_path": "assets/images/app_logo/cerita_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 7,
    "title": "[Cultural Exploration through Gameplay]\nBedugul Forest",
    "about": "Bedugul Forest is an educational game designed to introduce the Panca Yadnya Bedugul Museum through interactive media. In this game, players control a monkey that must avoid various obstacles while collecting prayer equipment. The game was created as part of a thesis project by a student at STMIK Primakara.",
    "outcome": ["STMIK Primakara Student Thesis 2019", "Achieved Grade A", "Graduated in 3.5 Years"],
    "timeline": "January 2019 - March 2019",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As a Game Programmer, I was responsible for identifying problems, designing solutions in the form of an interactive game, and compiling the final thesis report documenting the entire development process.",
    "tech_stack": "Construct 2",
    "app_title": "Bedugul Forest",
    "year": "2019",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/bedugul_detail.png",
    "icon_path": "assets/images/app_logo/bedugul_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 8,
    "title": "[72-Hour Multiplayer Creation]\nMenunggu Ayah̷m Pulang",
    "about": "Menunggu Ayah̷m Pulang is a multiplayer game developed in 72 hours as part of Global Game Jam 2019. In the game, players must quickly group chickens into the right place using the Air Console platform. The game utilizes inter-player connectivity to create an exciting and competitive gaming experience.",
    "outcome": ["Completed in 72 hours", "Multiplayer game with Air Console integration", "Used open source assets"],
    "timeline": "January 2019",
    "timeline_detail": "72 Hours of Development",
    "responsibility": "As a Game Programmer, I was responsible for designing fast and dynamic gameplay and integrating the game with the Air Console platform to support multiplayer.",
    "tech_stack": "Construct 2, Air Console API",
    "app_title": "Menunggu Ayah̷m Pulang",
    "year": "2019",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/ayam_detail.png",
    "icon_path": "assets/images/app_logo/ayam_thumbnail.png",
    "category": "Web Game",
    "device": ["assets/vectors/mdi--web.svg"]
  },
  {
    "id": 9,
    "title": "[Celebrating Asian Games 2018 with]\nMenuju Pesta Olahraga Asia",
    "about": "Menuju Pesta Olahraga Asia is a game developed to celebrate the Asian Games 2018. The game contains three challenging mini-games: rock climbing, running, and football. Players compete to achieve the highest score recorded in the leaderboard, creating a fun and competitive experience for all users.",
    "outcome": ["100+ Downloads", "Leaderboard integration", "Released on Google Play"],
    "timeline": "June 2018 - August 2018",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As a Game Programmer, I worked with designers to develop the entire game, including leaderboard integration, ensuring the game runs smoothly on the Android platform.",
    "tech_stack": "Construct 2",
    "app_title": "Menuju Pesta Olahraga Asia",
    "year": "2018",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/rtga_detail.png",
    "icon_path": "assets/images/app_logo/rtga_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 10,
    "title": "[3 Years of Educational Fun]\nShimajiro Education Game",
    "about": "Shimajiro Education Game is a series of educational web games based on the popular Japanese cartoon character 'Shimajiro'. The games are designed to teach children various skills and can be accessed through the Shimajiro website. Over three years, the project consistently released new games focused on interactive and fun learning.",
    "outcome": ["Released new games regularly for 3 years", "Published a total of 10 games", "Received positive feedback from users"],
    "timeline": "April 2018 - July 2020",
    "timeline_detail": "3 Years of Development",
    "responsibility": "As a Game Programmer, I collaborated with designers and communicated with clients to design and develop educational and engaging games for children. I was responsible for all technical aspects of game development.",
    "tech_stack": "Construct 2",
    "app_title": "Shimajiro Education Game",
    "year": "2018 - 2020",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/shimajiro_detail.png",
    "icon_path": "assets/images/app_logo/shimajiro_thumbnail.png",
    "category": "Web Game",
    "device": ["assets/vectors/mdi--web.svg"]
  },
  {
    "id": 11,
    "title": "[Engaging Kids in English Learning]\nLipi Poleng Tanah Lot",
    "about": "Lipi Poleng Tanah Lot is an educational game designed to teach English to elementary school children through interactive Balinese folklore. The game includes English voice-overs that help children listen to stories and enhance their ability to understand English.",
    "outcome": ["Educational game in English", "First portrait-oriented game", "Uses custom voice-over"],
    "timeline": "September 2020 - October 2021",
    "timeline_detail": "1 Year of Development",
    "responsibility": "As a Game Programmer, I designed an interactive English-language educational game, coordinated with researchers to ensure the game effectively teaches the language, and worked with voice talent to ensure the voices fit the game context.",
    "tech_stack": "Contruct 2",
    "app_title": "Lipi Poleng Tanah Lot",
    "year": "2021",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/lipi_poleng_detail.png",
    "icon_path": "assets/images/app_logo/lipi_poleng_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 12,
    "title": "[Save the Egg, Solve the Puzzle]\nLost Egg",
    "about": "Lost Egg is a physics-based puzzle game where players must remove wooden blocks that block the hen and egg. The challenge is to keep the egg from breaking when it falls to the ground. The game features engaging and challenging mechanics, testing the player's ingenuity in solving each level.",
    "outcome": ["Participant in Compfest 9", "Attracted publisher interest and was acquired", "Consists of 10 game levels"],
    "timeline": "July 2017 - April 2019",
    "timeline_detail": "2 Years of Development",
    "responsibility": "As the Lead Team, I designed the game concept, developed the code, and coordinated the team to ensure the game ran well in terms of gameplay and technical implementation.",
    "tech_stack": "Construct 2",
    "app_title": "Lost Egg",
    "year": "2019",
    "role": "Lead Team",
    "link": "",
    "image_path": "assets/images/app_screenshot/lost_egg_detail.png",
    "icon_path": "assets/images/app_logo/lost_egg_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 16,
    "title": "[Empowering Local Shopping]\nPande Putri Go",
    "about": "Pande Putri Go is an e-commerce application designed to facilitate the buying and selling of goods from large supermarkets with many branches in Denpasar. The application provides convenience for customers to shop through a platform integrated with local supermarkets.",
    "outcome": ["Android app released on Google Play", "iOS app released on the App Store", "Achieved a 5.0 rating on the App Store"],
    "timeline": "September 2022 - November 2023",
    "timeline_detail": "14 Months of Development",
    "responsibility": "As a Mobile App Developer, I was responsible for developing the application using React Native, updating features based on client requests, and fixing bugs to ensure the application functioned optimally.",
    "tech_stack": "React Native",
    "app_title": "Pande Putri Go",
    "year": "2023",
    "role": "Mobile App Developer",
    "link": "",
    "image_path": "assets/images/app_screenshot/ppgo_detail.png",
    "icon_path": "assets/images/app_logo/ppgo_thumbnail.png",
    "category": "Android & iOS Application",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 18,
    "title": "[Anonymous Food Review Experience]\nSecret Bitess",
    "about": "Finding delicious food in Batam is not actually difficult. However, most recommendations come from word-of-mouth, with few shared online. This scarcity of online reviews is often due to fear of negatively impacting restaurants and receiving no benefits in return.\n\nIntroducing Secret Bitess: An app for anonymously reviewing food.",
    "outcome": ["Mockup completed in 3 months", "First time using Sketch", "Design conforms to Human Interface Guidelines (HIG)"],
    "timeline": "February 2024 - April 2024",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As a Researcher and UI/UX Designer, I conducted the entire process, from creating mockups with Sketch, conducting user needs research, to designing according to Human Interface Guidelines (HIG).",
    "tech_stack": "Sketch",
    "app_title": "Secret Bitess",
    "year": "2024",
    "role": "Researcher, UI/UX Designer",
    "link": "",
    "image_path": "assets/images/app_screenshot/secret_bitess_detail.png",
    "icon_path": "assets/images/app_logo/secret_bitess_thumbnail.png",
    "category": "Mockup Application",
    "device": ["assets/vectors/fluent--design-ideas-16-filled.svg"]
  },
  {
    "id": 19,
    "title": "[Stay on Schedule with a Feline Twist]\nCativity",
    "about": "An application that helps students become more time-conscious by taking care of a digital cat representing their activities, enabling them to follow through with their planned tasks.",
    "outcome": ["App that can remind students of their schedule", "App designed following Human Interface Guidelines (HIG)", "Managed the programmer team well, ensuring all code was used optimally"],
    "timeline": "April 2024 - June 2024",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As a Researcher, Animator, and Programmer, I worked in a team to manage tasks among programmers, conducted research on student needs, created prototypes, and developed interactive animations with Lottie.",
    "tech_stack": "SwiftUI, SwiftData, UserNotification, WidgetKit, LiveActivity, Lottie, Figma",
    "app_title": "Cativity",
    "year": "2024",
    "role": "Researcher, Animator, Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/cativity_detail.png",
    "icon_path": "assets/images/app_logo/cativity_thumbnail.png",
    "category": "iOS Application",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 14,
    "title": "[Teaching Financial Literacy through Play]\nAyo Menabung",
    "about": "Ayo Menabung is an educational game that teaches children the importance of saving by collecting garbage that can be exchanged for money. The money collected can be used to buy skins in the game. There are 5 stages that players must go through, providing a fun and interactive learning experience.",
    "outcome": ["Released on Google Play", "Led the team well", "Successfully translated client requests into a functional game"],
    "timeline": "March 2022 - August 2022",
    "timeline_detail": "6 Months of Development",
    "responsibility": "As a Game Programmer, I was responsible for developing the app, designing gameplay, and setting specifications for designers. I also ensured client requests were well translated into game features.",
    "tech_stack": "Contruct 2",
    "app_title": "Ayo Menabung",
    "year": "2022",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/ayo_menabung_detail.png",
    "icon_path": "assets/images/app_logo/ayo_menabung_thumbnail.png",
    "category": "Android Game",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 13,
    "title": "[Offline IoT Integration]\nCars",
    "about": "Cars is an iOS application that works entirely offline, connecting sensors on IoT devices to the app via Bluetooth Low Energy. The app is designed to receive and process sensor data, then convert it into readable information directly within the app without an internet connection.",
    "outcome": ["App released on TestFlight", "First offline app connected with IoT devices", "Works in both dark and light modes"],
    "timeline": "June 2023 - November 2023",
    "timeline_detail": "5 Months of Development",
    "responsibility": "As an iOS Programmer, I was responsible for developing the app, calculating the RAW values from device sensors, and converting that data into usable information within the app.",
    "tech_stack": "Swift, UIKit, BluetoothCore",
    "app_title": "Cars",
    "year": "2023",
    "role": "iOS Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/cars_detail.png",
    "icon_path": "assets/images/app_logo/cars_thumbnail.png",
    "category": "iOS Application integrated with iOT device",
    "device": ["assets/vectors/bi--phone.svg", "assets/vectors/carbon--iot-connect.svg"]
  },

  {
    "id": 17,
    "title": "[Fast E-Commerce Solutions]\nAppmu Indonesia",
    "about": "Appmu Indonesia is an e-commerce application template that can be easily customized according to client requirements, enabling app launches within a month. This project allows businesses to have custom e-commerce apps quickly, offering efficient solutions for over 10 clients.",
    "outcome": ["Android app released on Google Play", "iOS app released on the App Store", "Served over 10 clients"],
    "timeline": "March 2022 - February 2023",
    "timeline_detail": "12 Months of Development",
    "responsibility": "As a Mobile App Developer, I was responsible for developing the app in Android Studio for the native version and converting it to a React Native version. I also ensured the app could be quickly customized and released per client needs.",
    "tech_stack": "Kotlin, React Native",
    "app_title": "Appmu Indonesia",
    "year": "2023",
    "role": "Mobile App Developer",
    "link": "",
    "image_path": "assets/images/app_screenshot/appmu_detail.png",
    "icon_path": "assets/images/app_logo/appmu_thumbnail.png",
    "category": "Android & iOS Application",
    "device": ["assets/vectors/bi--phone.svg"]
  },
  {
    "id": 20,
    "title": "[Optimize Your Run with Music and Heart Rate Guidance]\nGRUN",
    "about": "GRUN is a watchOS application designed for runners, aiming to enhance running efficiency comfortably. The app uses personalized music to provide running guidance, ensuring stable and efficient performance in Heart Rate Zone 2. GRUN provides real-time feedback to keep the heart rate and pace at optimal levels, creating a healthier and more enjoyable running experience.",
    "outcome": ["App integrated with MusicKit and HealthKit", "Released on TestFlight", "Runs on iOS and watchOS"],
    "timeline": "June 2024 - July 2024",
    "timeline_detail": "25 Working Days",
    "responsibility": "As a Researcher and Lead Programmer, I worked in a team to manage tasks among programmers, conducted research on runner needs, and researched integration with MusicKit to provide optimal features.",
    "tech_stack": "SwiftUI, HealthKit, MusicKit, WatchKit",
    "app_title": "GRUN",
    "year": "2024",
    "role": "Researcher, Lead Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/grun_detail.png",
    "icon_path": "assets/images/app_logo/grun_thumbnail.png",
    "category": "iOS & WatchOS Application",
    "device": ["assets/vectors/bi--phone.svg", "assets/vectors/tdesign--watch.svg"]
  },
  {
    "id": 22,
    "title": "A Reflective Journey of Freedom\nEternal Night Shift",
    "about": "Eternal Night Shift: The Night Servant is a Macbook game that tells the story of a 'tuyul' (mythical creature) striving for freedom from servitude. Inspired by the creators' own experiences, it reflects a desire to work more peacefully without the pressure of constantly overproducing to achieve prosperity. The game offers unique and thoughtful gameplay tailored to the Macbook platform.",
    "outcome": ["Received 52 feedback points from exhibitions", "Developed using Unity within 25 working days", "0% crash rate on TestFlight"],
    "timeline": "July 2024 - August 2024",
    "timeline_detail": "25 Working Days",
    "responsibility": "As a Researcher and Programmer, I conducted research to define the appropriate game genre and target audience for Macbook users. Additionally, I developed the game from scratch and coordinated programmers to ensure seamless collaboration.",
    "tech_stack": "Unity SDK",
    "app_title": "Eternal Night Shift: The Night Servant",
    "year": "2024",
    "role": "Researcher, Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/tuyul.png",
    "icon_path": "assets/images/app_logo/tuyul_thumbnail.png",
    "category": "Macbook Application",
    "device": ["assets/vectors/ri--macbook-line.svg"]
  },
  {
    "id": 21,
    "title": "[Explore Chemistry in Augmented Reality]\nMolecule Mastery",
    "about": "Molecule Mastery is a multiplayer educational game aimed at making chemistry learning more competitive by motivating players to beat other players. The game combines the 'Atom' card game with Augmented Reality technology, allowing players to visualize chemical elements in 3D, thereby enhancing their understanding of molecular structures.",
    "outcome": ["Released on the App Store", "Received positive feedback from 8 SMAK Yos Sudarso Batam students", "Works well on iPad and iPhone"],
    "timeline": "June 2024 - July 2024",
    "timeline_detail": "2 Months of Development",
    "responsibility": "As a Researcher and Programmer, I conducted research on Augmented Reality and user needs, developed dynamic atom displays in the code, and ensured the quality of the code pushed to the main branch.",
    "tech_stack": "SwiftUI, UIKit, RealityKit, SceneKit",
    "app_title": "Molecular Mastery",
    "year": "2024",
    "role": "Mobile App Developer",
    "link": "",
    "image_path": "assets/images/app_screenshot/molecular_mastery_detail.png",
    "icon_path": "assets/images/app_logo/molecular_mastery_thumbnail.png",
    "category": "iOS Application & iPadOS Application",
    "device": ["assets/vectors/bi--phone.svg", "assets/vectors/icon-park-outline--ipad-one.svg"]
  },
  {
    "id": 15,
    "title": "[Therapeutic VR Gaming]\nHealing Pod Game",
    "about": "Healing Pod Game is a Virtual Reality-based game connected to various IoT devices and designed specifically for therapy for children with folio conditions and adults with mild strokes. The game consists of 5 mini-games designed to provide an effective therapeutic experience through virtual interactions that support the healing process.",
    "outcome": ["Bug-free Virtual Reality game", "Used on pod devices for therapy", "Game that supports health therapy"],
    "timeline": "August 2023 - October 2023",
    "timeline_detail": "3 Months of Development",
    "responsibility": "As a Game Programmer, I was responsible for developing the app, optimizing game assets to be lightweight, and integrating various IoT devices used in therapy.",
    "tech_stack": "Unity XR",
    "app_title": "Healing Pod Game",
    "year": "2023",
    "role": "Game Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/healingpod_detail.png",
    "icon_path": "assets/images/app_logo/healingpod_thumbnail.png",
    "category": "Virtual Reality Game",
    "device": ["assets/vectors/hugeicons--virtual-reality-vr-01.svg"]
  },
  {
    "id": 23,
    "title": "Where Space Meets Intelligence\nSpatia!",
    "about": "Spatia! is an innovative iOS and iPadOS application that empowers non-interior designers to analyze and optimize their living spaces. Using advanced RoomPlan and SpriteKit technology, Spatia! enables users to scan and create a digital floor plan of their rooms, helping them arrange furniture for various activities to maximize comfort and functionality.",
    "outcome": ["4.8/5 rating on App Store", "0% crash on the last 3 updates", "Selected as one of the top 5 teams from Apple Developer Academy Batam for the government showcase selection"],
    "timeline": "October 2024 - November 2024",
    "timeline_detail": "3 Months Development",
    "responsibility": "As  Programmer, I fixed scanning features from older versions, added functionality for selecting items from Rupa-Rupa and manually adding furniture, resolved UI bugs in older features, and as Project Manager ensured all tasks were completed on schedule.",
    "tech_stack": "SwiftUI, UIKit, SwiftData, RoomPlan, SpriteKit, SceneKit",
    "app_title": "Spatia!",
    "year": "2024",
    "role": "Project Manager, Programmer",
    "link": "",
    "image_path": "assets/images/app_screenshot/spatia.png",
    "icon_path": "assets/images/app_logo/spatia_thumbnail.png",
    "category": "iOS & iPadOS Application",
    "device": ["assets/vectors/bi--phone.svg", "assets/vectors/icon-park-outline--ipad-one.svg"]
  }
];
